export const ProductOptions = {
  Capacity: [1, 2, 3, 5, 7.5, 10, 12.5, 15, 20],
  Span: [
    5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
    25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
  ],
  Height_of_lift: ["7.0 MTR.", "11.0 MTR."],
  Travel_Length: ["50.0 MTR."],
  Area_Classification: [
    "SAFE",
    "HAZARDOUS ZONE 1 IIA/IIB T3",
    "HAZARDOUS ZONE 1 IIC T3",
    "HAZARDOUS ZONE 2 IIC T3",
    "HAZARDOUS ZONE 2 IIA/IIB T3",
    "HAZARDOUS",
  ],
  Location: ["INDOOR", "OUTDOOR"],
  Ambient_Temp: ["40", "45", "50"],
  Class: [
    "CLASS II & MEDIUM DUTY",
    "M5 MEDIUM DUTY",
    "CLASS III & HEAVY DUTY",
    "M6 HEAVY DUTY",
    "M7 HEAVY DUTY ",
    "CLASS IV HEAVY DUTY & HEAVY DUTY",
    "M8 HEAVY DUTY",
  ],
  Power_Supply: [
    "415 V (+/-10%) 3 Ph 50 Hz (+/-5%)",
    "380 V (+/-10%) 3 Ph 50 Hz (+/-5%)",
  ],
  Control_Voltage: ["110V 1 PH", "24V 1 PH", "48V 1 PH", "220V 1 PH"],
  Crane_Quantity: ["01 NO."],
  IS_Standard: ["IS:3177 & IS:807"],
  Operation: [
    "NA",
    "PENDANT PUSH BUTTON STATION",
    "RCC",
    "CABIN OPERATED",
    "PENDANT PUSH BUTTON STATION+RRC",
    "PENDANT PUSH BUTTON STATION+RRC+CABIN",
  ],
  Speeds_mpm: ["HOIST - C.T. - L.T."],
  HOIST: ["5.0*", "3.0/1.0*"],
  C_T: ["15.0*", "15.0/1.5*"],
  L_T: ["20.0*", "20.0/2.0*"],
  Main_Micro: ["5.0* - 15.0* - 20.0*", "3.0/1.0* - 15.0/1.5* - 20.0/2.0*"],
  Motors: [
    "AC SQ CAGE INDUCTION MOTOR 40% CDF 150S-S/Hr S1/S4 DUTY",
    "AC SLIP RING INDUCTION MOTOR 40%CDF 150S-S/Hr S1/S4 DUTY",
  ],
  H_P__K_W: [
    "5.5 - 1.1 - 1.1",
    "10/7.5 - 2.0/1.5 - 3.0/2.2",
    "5.5/7.5 - 1.1/1.5 - 1.1/1.5",
  ],
  Motors_H_P__K_W_HOIST: [
    "NA",
    "VFD",
    0.5,
    0.75,
    1,
    1.5,
    2,
    3,
    5,
    7.5,
    10,
    12.5,
    15,
    20,
    25,
    30,
    40,
    50,
    60,
  ],
  Motors_H_P__K_W_C_T: [
    "NA",
    "VFD",
    0.5,
    0.75,
    1,
    1.5,
    2,
    3,
    5,
    7.5,
    10,
    12.5,
    15,
    20,
    25,
    30,
    40,
    50,
    60,
  ],
  Motors_H_P__K_W_L_T: [
    "NA",
    "VFD",
    0.5,
    0.75,
    1,
    1.5,
    2,
    3,
    5,
    7.5,
    10,
    12.5,
    15,
    20,
    25,
    30,
    40,
    50,
    60,
  ],
  Motors_Make: ["BBL/CGL - BBL/CGL - SEW", "BBL/CGL - BBL/CGL - BBL/CGL"],
  Motors_Make_HOIST: [
    "NA",
    "CG/LHP",
    "BBL",
    "BBL/CG",
    "CG",
    "SAFEX",
    "LHP",
    "MARATHON",
    "SEW",
    "NORD",
    "BBL/CG/LHP",
    "SEW/NORD",
  ],
  Motors_Make_C_T: [
    "NA",
    "CG/LHP",
    "BBL",
    "BBL/CG",
    "CG",
    "SAFEX",
    "LHP",
    "MARATHON",
    "SEW",
    "NORD",
    "BBL/CG/LHP",
    "SEW/NORD",
  ],
  Motors_Make_L_T: [
    "NA",
    "CG/LHP",
    "BBL",
    "BBL/CG",
    "CG",
    "SAFEX",
    "LHP",
    "MARATHON",
    "SEW",
    "NORD",
    "BBL/CG/LHP",
    "SEW/NORD",
  ],
  Motors_QTY: ["01 NO. - 01 NO. - 02 NOS."],
  Brake: ["FAIL TO SAFE TYPE"],
  Brake_Type: [
    "AC EM SHOE - AC EM DISC - DC EM ",
    "AC EHT - AC EHT - AC EHT",
    "AC EM SHOE - AC EM DISC - DC EM SHOE",
    "AC EHT - AC EHT - DC EM ",
  ],
  Brake_Type_HOIST: [
    "AC EM SHOE",
    "AC EM DISC",
    "DC EM SHOE",
    "DCEM DISC",
    "AC EHT SHOE",
  ],
  Brake_Type_C_T: [
    "AC EM SHOE",
    "AC EM DISC",
    "DC EM SHOE",
    "DCEM DISC",
    "AC EHT SHOE",
  ],
  Brake_Type_L_T: [
    "AC EM SHOE",
    "AC EM DISC",
    "DC EM SHOE",
    "DCEM DISC",
    "AC EHT SHOE",
  ],
  Brake_Make: [
    "SAFEX - SAFEX - SAFEX",
    "EMM/SOC - EMM/SOC - EMM/SOC",
    "EMM/SOC - EMM/SOC - SAFEX",
  ],
  Brake_Make_HOIST: [
    "NA",
    "EMM",
    "SOC",
    "EMM/SOC",
    "SAFEX",
    "BCH",
    "PETEH",
    "SYTCO",
    "EMCO",
    "SEW",
    "NORD",
    "SEW/NORD",
  ],
  Brake_Make_C_T: [
    "NA",
    "EMM",
    "SOC",
    "EMM/SOC",
    "SAFEX",
    "BCH",
    "PETEH",
    "SYTCO",
    "EMCO",
    "SEW",
    "NORD",
    "SEW/NORD",
  ],
  Brake_Make_L_T: [
    "NA",
    "EMM",
    "SOC",
    "EMM/SOC",
    "SAFEX",
    "BCH",
    "PETEH",
    "SYTCO",
    "EMCO",
    "SEW",
    "NORD",
    "SEW/NORD",
  ],
  Brake_QTY: ["01 NO. - 01 NO. - 02 NOS."],
  Limit_Switch: ["HOIST - C.T. - L.T."],
  Limit_Switch_Type: [
    "ROLLER TYPE - ROLLER TYPE - 2 WAY LEVER TYPE",
    "ROTARY+GRAVITY - 2 WAY LEVER TYPE - 2 WAY LEVER TYPE",
  ],
  Limit_Switch_Type_HOIST: [
    "NA",
    "ROTARY",
    "ROLLER",
    "GRAVITY",
    "LEVER",
    "ROLLER+GRAVITY",
    "ROTARY+GRAVITY",
    "ROTARY+ROLLER",
  ],
  Limit_Switch_Type_C_T: [
    "NA",
    "ROTARY",
    "ROLLER",
    "GRAVITY",
    "LEVER",
    "ROLLER+GRAVITY",
    "ROTARY+GRAVITY",
    "ROTARY+ROLLER",
  ],
  Limit_Switch_Type_L_T: [
    "NA",
    "ROTARY",
    "ROLLER",
    "GRAVITY",
    "LEVER",
    "ROLLER+GRAVITY",
    "ROTARY+GRAVITY",
    "ROTARY+ROLLER",
  ],
  Limit_Switch_Make: [
    "AVON/BCH - AVON/BCH - EMM/SOC",
    "EMM/SOC - EMM/SOC - EMM/SOC",
  ],
  Limit_Switch_Make_HOIST: [
    "NA",
    "EMM",
    "SOC",
    "SNT",
    "EMM/SOC",
    "AVON",
    "BCH",
    "AVON/BCH",
    "SIEMENS",
    "GIOVENZANA",
    "AVON/BCH+SOC",
  ],
  Limit_Switch_Make_C_T: [
    "NA",
    "EMM",
    "SOC",
    "SNT",
    "EMM/SOC",
    "AVON",
    "BCH",
    "AVON/BCH",
    "SIEMENS",
    "GIOVENZANA",
    "AVON/BCH+SOC",
  ],
  Limit_Switch_Make_L_T: [
    "NA",
    "EMM",
    "SOC",
    "SNT",
    "EMM/SOC",
    "AVON",
    "BCH",
    "AVON/BCH",
    "SIEMENS",
    "GIOVENZANA",
    "AVON/BCH+SOC",
  ],
  Limit_Switch_QTY: [
    "01 NO. + 01 NO. - 01 NO. + 01 NO. - 01 NO.",
    "01 NO. + 01 NO. - 01 NO. - 01 NO.",
  ],
  Wheel: ["∅135 - ∅160", "∅160 - ∅320"],
  Wheel_HOIST: ["-"],
  Wheel_C_T: ["Ø115", "Ø125", "Ø135", "Ø184", "Ø210"],
  Wheel_L_T: ["Ø160", "Ø200", "Ø250", "Ø320", "Ø400", "Ø500", "Ø630"],
  Wheel_QTY: ["04 NOS. - 04 NOS."],
  Rail_Size_HOIST: ["-"],
  Rail_Size_C_T: ["-"],
  Rail_Size_L_T: [
    "SQ. 40",
    "SQ. 50",
    "REC. 50x40",
    "SQ. 60",
    "REC. 60x50",
    "REC. 60x40",
    "SQ. 65",
    "SQ. 70",
    "REC. 70x60",
    "REC. 70x50",
    "REC. 70x40",
    "SQ. 75",
    "25 LBS",
    "30 LBS",
    "35 LBS",
    "40 LBS",
    "50 LBS",
    "60 LBS",
    "75 LBS",
    "90 LBS",
    "105 LBS",
    "120 LBS",
    "CR 50",
    "CR 60",
    "CR 80",
    "CR 100",
    "CR 120",
    "CR 140",
  ],
  Rail_Size: ["50x40 mm REC. BAR", "40 mm SQ. BAR - 50x40 mm REC. BAR"],
  Type_of_Motion: [
    "*ALL MICRO MOTIONS ARE WITH VVVF DRIVE. (MAKE: SCHNEIDER/ABB)",
    "*ALL MICRO MOTIONS ARE WITH VVVF DRIVE. (MAKE: SCHNEIDER)",
  ],
  No_of_falls: ["2 FALLS", "4 FALLS", "8 FALLS"],
  Wire_Rope_Size_Const: [
    "∅14mm,6x36 CONST.,STEEL CORE, IS:2266, 1960N/mm2, (MAKE: USHA MARTIN)",
    "*ALL MICRO MOTIONS ARE WITH VVVF DRIVE. (MAKE: SCHNEIDER)",
    "*ALL MICRO MOTIONS ARE WITH VVVF DRIVE. (MAKE: SCHNEIDER/ABB)",
  ],
  Hook_Type: ["C TYPE", "RAMSHORN TYPE"],
  Hook: ["FORGED STEEL,IS:3815/IS:15560, (MAKE:EEK)"],
  C_T_Power_Feeding: ["C-TRACK TYPE FEEDING ARRANGEMENT"],
  L_T_Power_Feeding: [
    "4 WAY SHROUDED ARRANGEMENT WITH ALL ACCESSORIES",
    "FESTOONED CABLE ARRANGEMENT ALL ACCESSORIES",
  ],
  Buffer: ["RUBBER BUFFER", "SPRING BUFFER"],
  Platform: ["SHORT PLATFORM ON BOTH SIDE"],
  Painting: [
    "2 COATS OF RED OXIDE & 2 COATS SYNTHETIC GOLDEN YELLOW",
    "2 COATS OF EPOXY PRIMER & 2 COATS EPOXY GOLDEN YELLOW",
  ],
  Hooter: [".", "HOIST", "CT", "LT", "ALL MOTIONS"],
  Anti_Collision: ["NA", "WILL BE PROVIDED IN L.T. MOTION."],
  Bridge_Light: ["NA", "WILL BE PROVIDED IN L.T. MOTION."],
  Dsl_Maintenance_Cage: ["NA", "WILL BE PROVIDED IN L.T. MOTION."],
  Load_cell: ["NA", "WILL BE PROVIDED IN L.T. MOTION."],
  Jacking_Pad: ["NA", "WILL BE PROVIDED FRO L.T.", "WILL BE PROVIDED FRO C.T."],
  Crane_Weight: ["4.1 TON. (APPROX.)", "20.0 TON. (APPROX.)"],
  Wheel_Load: ["3.65 TON. (APPROX.)", "10.5 TON. (APPROX.)"],
};
